// <auto-generated>
// Rewired Constants
// This list was generated on 27/04/2019 13:05:51
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal Movement")]
        public const int MoveX = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical Movement")]
        public const int MoveY = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Start")]
        public const int Start = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIStart")]
        public const int UIStart = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIConfirm")]
        public const int UIConfirm = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIVertical")]
        public const int UIVertical = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Skill1")]
        public const int Skill1 = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Skill2")]
        public const int Skill2 = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Skill3")]
        public const int Skill3 = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Skill4")]
        public const int Skill4 = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal aiming")]
        public const int AimX = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical aiming")]
        public const int AimY = 17;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 1;
    }
    public static partial class CustomController {
    }
}
